# Generated by Django 4.2.6 on 2023-11-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipes_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='recipes',
            name='description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='cooking_time',
            field=models.FloatField(help_text='in minutes'),
        ),
    ]
