# Generated by Django 4.2.6 on 2023-11-10 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_ingredient_profile_recipe_recipeingredient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='diffiuclty',
            new_name='difficulty',
        ),
    ]
